### ISSUE TITLE
Server crashing while initiating

### ISSUE THREAD

**Issue by SinisterHeretic** [FTBTeam/FTB-Interactions#1032]
## Modpack Version: 
2.0.4

## Bug Report:
Server Won't Initiate

## Expected Behavior/Suggestions:
The server was running fine on 2.0.3, updated to 2.0.4 this morning and it crashes every time I go to start it.

## Is It Repeatable? Steps to Reproduce: 
1. Everytime the server starts it gives the same errors

## Link to Log or Crash File Paste**: 
Crash Report
https://paste.feed-the-beast.com/view/87265cba

Debug Report
https://paste.feed-the-beast.com/view/0380bf9b

**Comment by TeamDman** [comment]
@Saereth Is there a direct link to the server files they could try?

**Comment by Saereth** [comment]
No the FTB App auto generates them and fails to download for people quite frequently, its really problematic right now and I get a ton of reports due to app failures atm. Reinstalling once or sometimes even twice generally fixes it, or you can just use the client files and upload them since they are identical
