### ISSUE TITLE
Warnings about contenttweaker resource location mismatch in Linux

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [FTBTeam/FTB-Interactions#1033]
## Modpack Version: 
2.0.4

## Bug Report:
While booting up the pack, I saw several warnings that resource location capitalization was mismatched for some contenttweaker items and would not work in environments such as Linux, which treat different capitalization as different files. This occurs for the skystonelense item and cloudsHD

## Expected Behavior/Suggestions:
Resource Locations names should match

## Is It Repeatable? Steps to Reproduce: 
Launch the game and see the warnings in the log

## Link to Log or Crash File Paste**: 
https://gist.github.com/ALongStringOfNumbers/7deca83e82c4d77426084674236ca0ce
Here is the log where the warnings can be seen. Search for "Linux" to easily find the affected items

## Known Fix: 
Match the file name capitalization

**Comment by bcmpinc** [comment]
I've seen this issue in another mod-pack and its a bit more complicated than just the capitalization of filenames. Filenames should all be lower-case. The real issue is in the zen script itself, for example:
```zs
var zsBlockj = VanillaFactory.createBlock("portalBlockt", <blockmaterial:rock>);
```
According to the contenttweaker API, arguments to createBlock (and similar commands) must be lower case only.

Fixing capitalization of filenames won't work, as contenttweaker will use the capitalized filename in some places while it uses the lowercase filename in others.
