### ISSUE TITLE
Make obsidian requiring 4k emc a bit more obvious

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#109]
people having issue, clarity improvement

Submitter: `FTB Interactions#2470`
Body: `**[TeamDman_9201]** OwO issue "Make obsidian requiring 4k emc a bit more obvious" "people having issue, clarity improvement"`
Attachments:

**Comment by John-DND** [comment]
But 4k EMC isn't that hard to get. Just shear some leaves; they're 16 apiece so you only need four stacks per block.

**Comment by Vyraal1** [comment]
Not really sure how to make it more obvious, should we just state in the questook that items dont appear in the table if you don't have enough EMC for them?

**Comment by TheonlyTazz** [comment]
Isnt that Obvious? people really need to learn to read the Quests
![image](https://user-images.githubusercontent.com/3908847/55290726-00eb3780-53d7-11e9-998a-332258afcdd9.png)

**Comment by DelfCo** [comment]
Suggestion: in the tip text for The Wood Barber, after "A true expert min-maxes EMC production at all stages", add "You'll need a lot of EMC to get obsidian to even show up."

That puts it out there, but doesn't beat anyone over the head about it.

**Comment by TheonlyTazz** [comment]
it already tells people about it in the actual obsidian quest that there is a magical transmutation block (Transmutation table maybe!?) so i think this is redundant and people just need to read the quests

**Comment by DelfCo** [comment]
The quest text tells people to go to the tablet. It doesn't tell them about needing enough EMC. That's a thing you don't know if you haven't used Project E before, or if you've used Project E in most other packs, where you start with zero EMC and learn naturally that as you add EMC you see more things in the tablet. In this pack, even the behavior of the Tome of Knowledge isn't the same as usual. Assuming that this is a problem for the people who've reported it because "they just need to read the quests" isn't fair -- you don't know that they didn't read them. You only know that they ran into a stumbling block that could be easily removed.  I've seen two different YouTubers trip over this before remembering how it works. 

It costs almost nothing to clarify the hint a little more. The starter island isn't supposed to be the place where this pack is difficult.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55367491-5e58b480-54bb-11e9-880b-2d12e3633ac3.png)
