### ISSUE TITLE
Allow Chiseled stone varieties to be cut with Forge Microblocks saw

### ISSUE THREAD

**Issue by Hekera** [FTBTeam/FTB-Interactions#1121]
## Modpack Version: 
2.0.6

In a recent pack update many more blocks (those from Chisel in particular) were added to the microblocks whitelist. However, the "Double Slab" and "Seamless Double Slab" stone variants were not added, as they were introduced in a newer version of Chisel. Other variants of stone can already be cut.

**Comment by Cata-bre** [comment]
How are blocks added to the microblocks whitelist?

**Comment by Saereth** [comment]
There are alot more blocks that could be added as well but the truth is I just dont have time to keep up with requests of this nature so rather than set a precedent I'll just say feel free to add them and submit the additions here and I'll gladly add in any blocks you like. You can edit the microblocks.cfg file and make any additions and then open back here with an issue and I'll get them in
