### ISSUE TITLE
SFM dupe

### ISSUE THREAD

**Issue by algul** [FTBTeam/FTB-Interactions#1205]
## Modpack Version: 
2.0.9

## Bug Report:
Using Super factory manager to move items from GT machines can dupe whatever is extracted if the output is set to be limited.

## Is It Repeatable? Steps to Reproduce: 
1. Place GT Fluid solidifier, power it, add nugget mold, add liquid nightmares -> it will start producing infinity grains
2. Using Super factory manager, setup trigger->input solidifier->output chest(limit output to 16 infinity grains)   
3. Remove some grains from chest, SFM will refill it up to 16

If you remove the right amount, the output slot in fluid solidifier will start to fill above 64 without processing, just every tick it will climb up a bit more. You can remove grains from the output slot and they will stay in inventory even after reloading. Output slot in the machine will reset to 64 after re-log.
Works with other machines too, tested alloy smelter and furnace. Best chance of triggering is when the recipe has more then 1 item result(like 4 bronze ingots or 2 native clusters). 

## Mod/s Affected: 
Super factory manager
GT

## Known Fix: 
none at this time, still testing

**Comment by Saereth** [comment]
please report to SFM github, this is a mod issue, not a pack issue
https://github.com/TeamDman/SuperFactoryManager

As with most modded packs there are usually a dozen ways to dupe things if people chose to do so, best we can do is make sure the mod developers are aware and hope for a fix. 

Closing this because it isnt specifically a pack issue where I have any control over a fix other than updating the mod if a fix comes out (which I do as part of normal maintenance anyway)
