### ISSUE TITLE
Tanzanite Dust

### ISSUE THREAD

**Issue by Takkong** [FTBTeam/FTB-Interactions#1232]
## Modpack Version: 
2.0.9
## Bug Report:
I am unable to use the Autoclave to change Tanzanite Dust into Tanzanite.

## Expected Behavior/Suggestions:
Since most Gem dust can be converted to gems with the autoclave and Tanzanite isn't gating anything. I expected there to be a recipe to use the autoclave to convert Tanzanite Dust into Tanzanite.

**Comment by Saereth** [comment]
nah thats not how gtce does gem dusts, you can autoclave the purified crushed variants (post ore washing) into the gems, or further process in a sifter (ideal way of processing gems) and the remaining dust if you really want more gems you can implosion compressor although those dusts are generally just dumped for electrolyzing since there arent many uses for actual tanzanite gems for example.
