### ISSUE TITLE
Issue Loading into a world

### ISSUE THREAD

**Issue by ghzdude** [FTBTeam/FTB-Interactions#1238]
## Modpack Version: 
FTB Interactions v2.0.9

## Bug Report:
Trying to load into a world is causing a ticking block exception. After removing the block in question, I am now receiving a ticking memory connection and ticking world.

## Expected Behavior/Suggestions:
Expected behavior is that the world should load

## Is It Repeatable? Steps to Reproduce: 

1. Place a GregTech cable next to a compact machine. The cable must be connected to a generator outside of the compact machine.
2. Within the compact machine, place a tunnel that points to the GT cable
3. Place a GT battery hull on the tunnel, so that power can be transmitted from the generator to the battery
4. Connect a GT energy consuming machine to the battery hull

I do not know if the issue is 100% reproducible. I can provide a video if requested.

## Link to Log or Crash File Paste**: 

https://pastebin.com/uRMKTMqy - Ticking Block
https://pastebin.com/9xfF4J21 - Ticking Connection
https://pastebin.com/5vaR5twi - Ticking World

## Mod/s Affected: 

Compact Machines 3
Gregtech Community Edition

**Comment by Saereth** [comment]
Connecting gt cables via CM is not supported and its not something I can fix packwise, you can attempt to take it up with compact machines as the issue is on their side, but I'm not sure if its still being actively developed. Basically just dont do it. You should be able to have forge automatically get rid of the problematic tile entities by setting removeErroringTileEntities=true in forge.cfg
