### ISSUE TITLE
2.0.10 Recipe Balance

### ISSUE THREAD

**Issue by hacatu** [FTBTeam/FTB-Interactions#1246]
A few of the changes in 2.0.10 could be considered too strong (or weak (nightmare chicken))

1. Field generators without osmium open up replication at LV whereas it was previously late HV at least.  Personally I don't know if I really mind this because replicating for epoxy and similar isn't really better than just making it.  But at least the disassembly recipe needs to be fixed and I think if the recipes are kept the osmium recipes should be completely removed and they should be craft with wires / assembler with fluid just with the different wire kinds.
2. The red matter nerfs were too much, previously 100 red matter needed to be crafted, now it's 2.  Maybe 16 or something would be a happy medium?
3. Toluene requirements are still very steep.  I don't have a problem with this though.
4. Magic energy absorbers being EV is probably excessive since they're pretty bad without tick acceleration.
5. Since the starmetal and UF6 recipes are HV, even without space one can get AE2 and all other things that need starmetal at HV.  I think it should be IV, although practically it isn't going to be abused much because of the osmium requirement.
6. I think vinteum should require at least an mk2 reactor, but it's probably better where it is because it means photofission is kinda sorta an option even in a no space run, and nothing else needs the mk2 that you need to get the key so it would be weird and not require any additional cleverness.
7. The nightmare chicken takes way too much infinity dust to be useful.  I used a wither skeleton spawner and not only does needing the nightmare chicken for the ender chicken ruin that method in a no space run, you need to automate grains of infinity to reasonably get the 721 you need anyway so get the chicken you need a farm, and I haven't run the numbers but if a grains of infinity gives about 5 buckets average then you'd be better off just melting those 721.

This probably isn't a comprehensive list and I hope other people weigh in on what they think about these changes.

**Comment by Saereth** [comment]
1) Im ok with fieldgens/replication that early, was a consequence I ended up noticing but ultimately was pretty happy with
the recipes do need fixing thats on my radar

2) seems good

3) Hmm... I'll think about what I could do here

4) ok thats fair, I could move it to hv

5) yeah I was hoping the osmium would be the limiting factor here, if it turns out not to be I may revisit it

6) meh lol

7) agree on most points except the nightmare chicken requirements are pretty much where I want them. It isnt meant as an alternative to never setting up a farm, its meant to be a long term solution/more server friendly once you've at least farmed them for a bit. This is essentially letting you run a small farm with just spikes or something for an afternoon to get enough to make the chicken vs setting up one and dealing with endermen tp prevention, drops etc indefinitely
