### ISSUE TITLE
Crash loop with concurrent modification exception

### ISSUE THREAD

**Issue by joral** [FTBTeam/FTB-Interactions#1263]
## Modpack Version: 
2.0.9

## Bug Report:
Server crash loop

## Expected Behavior/Suggestions:
Apologies that I cannot provide much information on this.  Last night everything seemed fine when I logged off the server.  This morning, the server was stuck in a crash loop.  

## Link to Log or Crash File Paste**: 
https://pastebin.com/0catGmc3

## Mod/s Affected: 
Not sure

## Known Fix: 
Not sure

**Comment by joral** [comment]
I'm checking with the only other person who plays on the server, but I don't believe she logged on at all last night

**Comment by Dexton** [comment]
I'm getting the same crash on 2.0.9 after restarting my server.
Tried restoring the world from backups and setting forge.cfg to remove erroring entities and tile entities, also tried updating Gregtech to the newest version since it is mentioned in the logs.
But none of this has any effect on the error.

Latest crash log: https://pastebin.com/Xd8T6hhB
