### ISSUE TITLE
Warp core not froming when using titanium blocks from GregTech

### ISSUE THREAD

**Issue by Etezzer** [FTBTeam/FTB-Interactions#1268]
## Modpack Version: 
2.0.9

## Bug Report:
Warp core not froming when using titanium blocks from GregTech.

## Expected Behavior/Suggestions:
Warp core should be forming when using GregTech titanium blocks.
Using the GregTech titanium blocks should form the warp core so it's most likely an oreDict thing.

## Is It Repeatable? Steps to Reproduce: 
Yes it is repeatable. Use the HoloProjector and select warp core, right click where you want it, place the corresponding blocks. Right click warp core block, red x in top left corner of multiblock.

## Link to Log or Crash File Paste**: 
Didn't cause a crash.

## Mod/s Affected: 
Advanced Rocketry

## Known Fix: 
Change into creative and use Vulpes library titanium blocks.

**Comment by Cata-bre** [comment]
You have to use Titanium Blocks from Vulpes Library.

**Comment by ALongStringOfNumbers** [comment]
AR changed the Warp Core to form from the oredict, <ore:blockWarpCoreRim> a few versions back. That could be what is causing this issue if the GTCE titanium did not get added to this oredict.

**Comment by 04Slash** [comment]
The intended solution is to place the Gregtech titanium in a crafting grid which will convert it over to the Libvupes titanium.

Since this issue is still open, may I suggest adding the oredict to the Gregtech Titanium? This would be a more intuitive fix the problem. [The script](https://pastebin.com/baDyh6Cd) is pretty simple to do and I tested this myself to ensure that it does work.

**Comment by Saereth** [comment]
added your fix with credit in the next update, thanks for researching the issue @04Slash
