### ISSUE TITLE
Cracker Unit Recipe is out of touch with its usefulness

### ISSUE THREAD

**Issue by SonOfTheStars** [FTBTeam/FTB-Interactions#1275]
## Modpack Version: 
2.0.9

## Bug Report:
The Cracker Unit multiblock recipe asks for EV Tier Circuits, while it is a 3x5x3 Multiblock that performs the exact same cracking recipes as an MV chemical reactor can in 1 1x1x1 space. The Cracking Unit thus is entirely useless, and has no reason to have this expensive a recipe. Its neither faster nor does it offer any benefit in power usage, space requirements or efficiency, while having a recipe 100x as costly as the Chemical reactor of the same power tier.

## Expected Behavior/Suggestions:
Suggestion: Put the cost of the cracking unit controller back down to HV or even MV tier and make it more efficient than the chemical reactor is, such that there is real incentive of using it. Potentially shift cracking entirely onto those units and away from the reactor.

## Is It Repeatable? Steps to Reproduce: 
N/A

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
GregTechCommunityEdition

## Known Fix: 
N/A

**Comment by Saereth** [comment]
so this was kind of an intentional call, we basically just decided for this pack we'd essentially make those crackers completely optional. You still get the advantage of multiblock overclocking performance increase but yeah other than that the reactors are strictly "cheaper"/easier single block solutions
