### ISSUE TITLE
Apotheosis enchant for Astral sorc smelting miss configured

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#131]
based on max level, min should be 1 https://i.imgur.com/xnrocsd.png https://i.imgur.com/lPDWxZl.png

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Apotheosis enchant for Astral sorc smelting miss configured" "based on max level, min should be 1 https://i.imgur.com/xnrocsd.png https://i.imgur.com/lPDWxZl.png"`
Attachments:

**Comment by Shadows-of-Fire** [comment]
This appears to be consistent for a number of enchantments.  The way these configs work is as follows:
Min Level -> The absolute minimum level of this enchantment that can appear.
Max Level -> The absolute maximum level of this enchantment that can appear.
Min Enchanting Power -> The minimum enchanting power that a table needs to pull an enchantment based on the level of the enchantment.
Min Enchanting Power -> The maximum enchanting power that a table may have to pull an enchantment based on the level of the enchantment.
```
Enchanting power = 
1 
+ level
+ a random number between 0 and 1/4 item enchantability
+ a random number between 0 and 1/4 item enchantability```

The enchanting power formulas are a function f(x) as defined by the EvalEx spec.  "x" is the level of the enchantment.  Setting min level > max level (as appears to be the case for many enchantments in Interactions) effectively disables them.  I don't think that was intentional.

@Saereth @Vyraal1 this is rather urgent since it effectively means that most enchantments can't be accessed.

**Comment by Saereth** [comment]
got it sorted for next update, definitely explains some weirdness I was seeing with the enchant tables
