### ISSUE TITLE
Game freezes/crashes when generating chunks in the nether

### ISSUE THREAD

**Issue by Emblin13** [FTBTeam/FTB-Interactions#188]
## Modpack Version: 
1.1.1

## Bug Report:
The game crashes or freezes and has to be shut down with task manager

## Is It Repeatable? Steps to Reproduce: 
It is repeatable. While in the nether, the game consistently freezes or crashes while generating new chunks. It seems to be made worse when render distance is higher, or if I'm moving faster. It occasionally crashes during the loading process as well.
This issue seems to have only begun since I updated to 1.1.1

## Other Information:
I am using 10GB of RAM
The pack is not modified in any way.

## Link to Log or Crash File Paste**: 
The error message given to me each time is "The game crashed whilst ticking entity
Error: com.udojava.evalex.Expression$ExpressionException: Missing operator at character position 3"
https://pastebin.com/4YELxUfG
https://pastebin.com/mtjTF8fH
https://pastebin.com/eadpdFZE

**Comment by nzminecraftDOTcom** [comment]
Looks like you have a ticking entity/block issue: Do this
To remove erroring entities (Mobs - skeletons etc) and tile entities (Pistons, crafting tables, interactive blocks...)

######Single player:######
Close out of your game completely.
Do a world/save backup before proceeding.
Go to the config folder for the modpack, look for forge.cfg
######Server:######
Close the server down fully using /stop
Backup ALL relevant files you have, worlds, configs etc.
Go to the relevant config file for the modpack having the issue - Locate "forge.cfg"

Find the lines:

"Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES."

Set this part to true:
B:removeErroringEntities=true

AND

"Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES."

Set this part to true:
B:removeErroringTileEntities=true

Now start your game and load the world. If all went well it should load just fine. You should now try to do what you were doing when the crash occured. If that succeeds. Stop your game, and reset both those settings back to false. If you have issues further on, you can try leaving them on true but heed the warnings they state in their description.

**Comment by Vyraal1** [comment]
How did you update the server? And do you mind pastebinning your Apotheosis config files?

**Comment by Emblin13** [comment]
I completely uninstalled the pack and reinstalled it as an earlier version, and it fixed the bug entirely. Thanks for the help, though.
