### ISSUE TITLE
Mod pack not updating 

### ISSUE THREAD

**Issue by HotDelphox** [FTBTeam/FTB-Interactions#285]
When I try to upgrade the pack on twitch it starts downloading then fails stating that it ‘Cannot find addon dependency 235328’

I have tried updating normally and updating to new profile and get the same error each time. I am currently on version 1.0.1

**Comment by OhYea777** [comment]
Mine comes up as 'Cannot find addon dependency 246640'

**Comment by Vyraal1** [comment]
https://www.minecraft.curseforge.com/projects/246640 leads to mystical agriculture which isn't even in the pack. Likewise for 235328 it is Food Expansion. Either there was something wrong with your maniest or the problem is on Twitch's end. My recommendation is to install into a new profile and transfer your world save over to that new profile, otherwise I'm not sure if there's anything we can do about this.
