### ISSUE TITLE
Suggestion: Auto unlock all Astral Tome chapters in Astral Sorcery

### ISSUE THREAD

**Issue by ToasterKoishi** [FTBTeam/FTB-Interactions#296]
## Modpack Version: 
1.2.0

## Expected Behavior/Suggestions:
Due to the nature of the modpack, many items and structures in Astral Sorcery are made available to players before they're expected to have unlocked the corresponding chapter in the Astral Tome. Good examples are the Tree Beacon and Starlight Infuser. Due to this, many players become confused about how these structures work, and must exit the game and use Discord/Google/etc to find an answer.

Additionally, the order in which constellation papers can be crafted also allow the player to get constellation papers with constellations they cannot see before they reach the usual point in AS that would let them see it in the sky. For example, Octans and Lucerna are made in the Luminous Crafting Table, but players need to make the Attunement Altar in the Starlight Crafting Altar and attune themselves before they can see those constellations in the telescope.

My suggestions are:
- Unlock all chapters in the Astral Tome for all players without them needing to actually do the usual tasks, perhaps via a quest that explains why they're getting full access.
- Move the recipes for every constellation to at least the Starlight Crafting Altar, which is required for the Attunement Altar, as the Attunement Altar is the first point where unlocking constellations is actually useful to the player.
- Move the recipes for every dim constellation to at least the Celestial Altar, which is required to craft the Observatory, which is needed to see and draw dim constellations.

## Mod/s Affected: 
Astral Sorcery

**Comment by hobnob11** [comment]
may i suggest, (if its actually possible to use commands to unlock astral stages) a similar "cheat" system that thaumcraft got in 1.2, i.e optional quests that unlock the stages.

**Comment by Saereth** [comment]
can you point to any multiblocks required for progression that players cant see how to build at the appropriate time? This shouldn't be the issue. Optional multiblocks that we make early like the infuser are not necessary for progression at the point they're available. This means expert players that are familiar with the mod know to use a sextant to see how its built, or can google it/go from memory. This is not enough of a concern for us to give research and progression bypasses in Astral which already has very light requirements and easy knowledge sharing for teams.

Same thing with the constellations, none of them are needed to progress when they unlock the tier altar they are gated to is because that is where we want the minium gating to occur, there is little harm in them waiting until later to craft/utilize them. 

Not saying we'll do nothing here, but we're probably going to just watch for future feedback for now
