### ISSUE TITLE
plate bending machines have no assembler recipe

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#323]
due to this, and a wrench not working properly in ae auto crafting... you can't auto craft them.

Submitter: `FTB Interactions#2470`
Body: `**[IRSmoh_]** OwO issue "plate bending machines have no assembler recipe" "due to this, and a wrench not working properly in ae auto crafting... you can't auto craft them."`
Attachments:

**Comment by Saereth** [comment]
we're not going through and adding piece meal assembler recipes to every machine that lacks them. I cant even think of a circumstance where you need to make so many plate bending machines that you have to autocraft them. If you can give a good use case scenario where this is necessary I'd consider it but otherwise #wontfix

**Comment by Vyraal1** [comment]
Agreed on what Sae said, finalizing the wontfix.
