### ISSUE TITLE
h2 4u and o2 cold4u are overlapped making it impossible to complete both

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#344]
tab affected: space, this kinda blocks all the subsequent chains from being completable

Submitter: `IRSmoh_#5048`
Body: `OwO issue "h2 4u and o2 cold4u are overlapped making it impossible to complete both" "tab affected: space, this kinda blocks all the subsequent chains from being completable"`
Attachments:

**Comment by IRSmoh** [comment]
fix is basically: change explosive to depend on h2 4u2 and delete the node under h2 4u2. bb has it fixed atm.

**Comment by IRSmoh** [comment]
actually just go over most of the space tab. 
![image](https://user-images.githubusercontent.com/2626462/56240816-fe851080-6059-11e9-9a2a-e957b3a2d233.png)
also overlaps.

and "unmanned rockets to space" > there is no need to send rockets off to collect research anymore since its been changed to just need artifacts to warp due to the.. fun in beta trying to get them to work for research.

**Comment by Vyraal1** [comment]
Changes made:
Deleted O2 quest, and redundant Vacuum Freezer quest in space tab.
Made the H2 4u2 quest dependent on vacuum freezer quest in ayo tech.
Clarified description.
![image](https://user-images.githubusercontent.com/26587049/56241780-bb7c6a80-6064-11e9-9795-064ac81bea18.png)

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/56247045-96dabf80-6071-11e9-8691-6f6403196cc4.png)
Moved unmanned rockets as predecessor to satellites

**Comment by Vyraal1** [comment]
Elected to keep unmanned rockets, quest but moving it towards the left as a dependency for the Satellites quest
