### ISSUE TITLE
Aurelia generated as terra's moon instead of luna

### ISSUE THREAD

**Issue by beastly123** [FTBTeam/FTB-Interactions#403]
## Modpack Version: 
1.3.0

## Bug Report:
Aurelia has generated next to Terra, and Terra has no moon. I used the advanced rocketry planet list feature and I have two aurelia planets. The issue persists through updates. I traveled to the planet, thinking it might just be a naming issue, but it does appear to actually be Aurelia.  -->

## Expected Behavior/Suggestions:
Bugs: Terra has no moon
 Suggestions: terra should have a moon 

## Is It Repeatable? Steps to Reproduce: 
I don't know how to repeat this bug, and I dont know how to fix it. Creating a new world has the correct planets and moons

## Link to Log or Crash File Paste**: 
no crash was involved

## Mod/s Affected: 
 Advanced rocketry

**Comment by Vyraal1** [comment]
Is there anything built on the planets / space stations? My advice would be deleting the `advRocketry` folder in your world save and then going back to reload those planets. Otherwise would advise re-downloading the pack and making sure the planetDefs.xml in your config/advRocketry looks like this; https://gist.github.com/Vyraal1/6b2b997e6719650f8490e5dc3dd8a07e

**Comment by Saereth** [comment]
Terra does not have a moon nor should it have a moon. Luna is the moon for void world, the questbook even specifically states this. That being said aurellia should never generate as a moon and could be some other issue if you're able to fly there with no artifact. please post a screenshot of your galaxy map and the contents of your /config/advancedrocketry/planetDefs.cfg as well as your world/advRocketry/planetdefs.cfg please
