### ISSUE TITLE
Tome of Knowledge is virtually worthless because HotOrNot

### ISSUE THREAD

**Issue by hyodocraft** [FTBTeam/FTB-Interactions#465]
## Modpack Version: 
1.2.1

## Bug Report:
Storing experience in the tome gives player Levitation II.

## Expected Behavior/Suggestions:
It should be usable without Mitts.

It's ridiculous to consume Mitts for use.
Especially auto-collecting exp.

## Is It Repeatable? Steps to Reproduce: 
1. Craft or cheat the tome
2. Use the tome to store exp in the tome
3. Levitate !

## Mod/s Affected: 
Thermal Foundation (Tome of Knowledge)
HotOrNot

**Comment by Vyraal1** [comment]
Going to have to disagree here, there are ways to store experience without also suffering these same effects, and want to keep this initial interaction as unique. In fact it comes off as a much more controllable form of flight with small amounts of experience than traditional bucket levitation using steam since you can just store experience in the tome and then absorb it back up.
