### ISSUE TITLE
Suggestion: Smart HUD

### ISSUE THREAD

**Issue by KaneHart** [FTBTeam/FTB-Interactions#497]
https://minecraft.curseforge.com/projects/smart-hud

Very simple and clean mod. It only shows new slots when the compass and or the clock are in your inventory. With a modpack like this where night / day, etc are quite important it really makes a great addition to the pack.

The slots don't show up or get in the way without the items in your inventory,

Also can add other items if you choose as well to it's whitelist :)

**Comment by Vyraal1** [comment]
Learning towards no on this one. 

Is this a clientside only mod? Since the pack is kinda bursting at the seams already with mods, we really want to avoid adding anything unless its necessary. Secondly, we also believe as devs, players should be monitoring their own clientside mods (sacred cows like my favorite CraftingTweaks got cut as a result). 

See here for similar reasoning: https://github.com/FTBTeam/FTB-Interactions/issues/137

**Comment by KaneHart** [comment]
Thanks. I can understand that. It's a server side mod as it adds a new special inventory to show / display the compass / clock. Thanks for your consideration :)
