### ISSUE TITLE
Fatal Java Runtime Environment Error

### ISSUE THREAD

**Issue by Hallowizer** [FTBTeam/FTB-Interactions#508]
## Modpack Version: 
1.3.0

## Bug Report:
I get an OS popup saying "Minecraft quit unexpectedly", and the Minecraft Launcher says that a fatal error was detected in the JRE.

## Expected Behavior/Suggestions:
I expect the JVM not to crash.

## Is It Repeatable? Steps to Reproduce: 
I do not know how to reproduce this. This happened once when I left the modpack open overnight, and when I got back, it had crashed. Today, I was looking up EnderIO items in JEI, and it crashed. I noticed in the logs that earlier today EnderIO's JEI plugin was giving errors.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/a2d3c334

## Mod/s Affected: 
The entire game is affected.

## Known Fix: 
I do not know of a fix.

**Comment by Hallowizer** [comment]
I just got another crash, when I looked up the recipe for Infinity Dust. https://paste.feed-the-beast.com/view/cd538cf4

**Comment by Vyraal1** [comment]
No idea on this one to be honest, maybe OS related? Could be memory related.

**Comment by Gunner76th** [comment]
@Hallowizer Please upload your log file located here:  /Users/hallowizer/Documents/Curse/Minecraft/Instances/FTB Interactions/hs_err_pid30745.log

**Comment by Gunner76th** [comment]
Additionally, what is your memory allocation set amount, what version of Java are you running, and how much physical memory is installed on your computer? 

The SIGSEGV that is noted in the first error you posted is 1) a highly difficult error to trace without access to the actual software code 2) is usually caused insufficient memory. Reference this issue due to its similarity in Java crash error: https://github.com/CraZySacX/node-jdbc/issues/65

As for your second error, the SIGABRT error, this is a Java error that is exclusive to Mac devices only, and has to do with trying to access memory that has been deallocated. If you can, please post all of the JVM arguments you are using, as well as your memory allocation settings. 

I would also suggest updating your Java to the most recent version. Based on the second error you posted, you are running version 191, the most recent is 211. While this is a fairly small version difference (compared to some individuals who are running update 51 or lower still) updating is generally a good place to start, ESP with errors that are happening at this level. The link to the download page is here: https://www.java.com/en/download/manual.jsp assuming you running an Intel based Mac. Based on your second error log, your OS version is sufficient as you are on version 10.14.4 and Java requires version 10.7.3

**Comment by Hallowizer** [comment]
When you say most recent version, are you talking about the most recent Java 8? I have seen that Java 9 and up don't work with Mojang's LaunchWrapper, which breaks Forge, due to classloading issues.

**Comment by Gunner76th** [comment]
Yes,  java 9 is not supported by forge or minecraft and likely never will without a full rewrite of the game's code base.

**Comment by Saereth** [comment]
this is os/config issue not something pack specific, not going to be able to offer much support for you on this one

**Comment by Hallowizer** [comment]
I just got the problem again, even after updating Java.

**Comment by Hallowizer** [comment]
https://paste.feed-the-beast.com/view/dd4eb228

**Comment by Gunner76th** [comment]
With this being a bad access error at the java/OS level, this is not a problem with the modpack itself. This is either a problem with the settings you are using during the launching of minecraft IE setting too much memory, a problem with your java installation, data/hardware corruption (such as a failing hard drive), or a problem with your OS. 

Also, do you have other modpacks installed, and do you have this same issue with them when all of the launch settings are the same? How much memory are you allocating to Minecraft on startup? Is the reported amount of memory (32 GB) accurate for how much is actually installed on your computer? When was the last time you checked for and installed any updates for your computer? (probably not going to help much, but it is always good to note when any updates were applied and if things started having problems afterwards. )

Your best option for resolving this issue is to look on Java focused forums, specifically those dealing with Apple computers and issues there in. Since Apple users make up a very small percentage of Minecraft players, the likelihood of finding a resolution within the Minecraft community is going to be slim.
