### ISSUE TITLE
You can make an absurd amount of fuel via the transmutation table

### ISSUE THREAD

**Issue by KingGorm** [FTBTeam/FTB-Interactions#517]
## Modpack Version: 
 1.4.1

## Bug Report:
You can make an absurd amount of fuel via the transmutation table

## Expected Behavior/Suggestions:
So with the transmutation table, sticks can be crafted into block of sticks which have a burn time of 300 ticks, so with a single block of obsidian you can make 4096 blocks of sticks that have a total burn time of 1,288,800 ticks, which is 38.4x more powerful then a  coal coke block
The easiest possible solution would be to remove the ability to use a block of sticks as fuel (ladders to a lesser degree as well)

**Comment by Kanzuke117** [comment]
Why are ladders the lesser degree? Same amount of sticks makes 3 ladders which have the same 300t burn time, and don't require any string.

That aside, I'm not sure this is absurd, really. If one were to try and use ladders or bundles to power their bronze boiler, each only lasts 6 ticks. Even if you filled a double chest with ladders in one huge batch craft, the boiler will have emptied it in 17 minutes.

Since there's no automatic way to extract sticks from an EMC tablet, your only hope of automating this is with logs -> wood -> sticks, which only nets you 900t of burn time per log, versus 1600t per by making it into charcoal

**Comment by Vyraal1** [comment]
Doubtful this is busted, as high as the number gets, it's still dependent on automated sticks (which at that point you might as well automate tree farms) or automated EMC (which should be impossible since you only have transmutation table).
