### ISSUE TITLE
Thaumium fiendishly unobvious

### ISSUE THREAD

**Issue by Torrenal** [FTBTeam/FTB-Interactions#519]
## Modpack Version: 
FTB Interactions 1.2.1

## Bug Report:
This modpack makes a point of disabling or modifying many many recipes.  This makes it normal to assume that recipes that can't be found were actually removed from the pack, and some alternate means was supplied to fill in for the missing recipe.  Thaumcraft itself also hides some recipes until things happen to make them available.  This combination makes it easy for someone to assume the default recipe for Thaumium was disabled.  Especially if they look at the sources for Thaumium Ingot (Gregtech Version), which has no crucible recipe, and appears in the JEI prior to the Thaumcraft version of the Thaumium ingot, and the Thaumium ingot recipe does not appear in the Thauminomicon (or rather, if it does show in the book, I've not done whatever voodoo it will take to unlock it)
 
## Expected Behavior/Suggestions:
Suggestions (any/all of)
* Reduce the Thaumium ingots to a single type.
* If possible, get the thaumium ingot to appear in the thauminomicon, or include a hint for making it appear.
* Get the crucible recipe to show for both Thaumim ingots

## Is It Repeatable? Steps to Reproduce: 
N/A

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Thaumcraft/Gregtech Community Edition

## Known Fix: 
N/A

**Comment by Vyraal1** [comment]
For the ingots where mods didn't hardcode interactions with items (Thaumcraft), we deprecated into one ingots. Not possible with Thaumium as some research depends on getting it. 

As for the Thaumium ingot not appearing in the book, that's because original recipe was removed, as far as I know there is no support to get it into the book for 1.12.2 Thaumcraft 6. Regardless it is in JEI, which is the primary source.
