### ISSUE TITLE
centrifuging sap drains more eu than expected.

### ISSUE THREAD

**Issue by Turmfalke2** [FTBTeam/FTB-Interactions#521]
hi,
The centrifuge recipe for sap -> glue appears to drain more than the stated 8 eu/t.

![2019-04-29_14 26 22](https://user-images.githubusercontent.com/5174562/56896217-6fc9b800-6a8b-11e9-9b2e-566bf64fa104.png)

On the right side I have basic steam turbine producing 32eu/t, on the left side is a basic centrifuge doing the sap -> glue recipe for 8 eu/t. The basic assembling machine in the middle isn't running due to missing items. If I let this run for a while the internal buffer of basic centrifuge empties itself and the machine stalls.

For this to happen the 2 pieces of 2x tin wire would have to cause an energy loss greater than 24 eu. No matter how loss this seems unlikely. So either the turbine isn't producing the 32eu or the recipe requires more than 8 eu/t. Given that I can run the 120eu recipes in the blast furnace with 4 of them I suspect it is the glue recipe.

## Modpack Version: 
1.4.1

**Comment by DrTasslehoff** [comment]
This is not actually an issue with the glue recipe, but how GT mechanics work. <=8EU is considered ULV power tier, so machines will overclock those recipes to LV. Doing so is making your 8EU recipe turn to a 32EU recipe.

**Comment by Turmfalke2** [comment]
but there isn't even an ulv centrifuge and by that logic every recipe would always require at least 32eu and therefor would be impossible to run without directly attaching the turbine to the machine. What is the point in having cables with power loss then?

**Comment by Vyraal1** [comment]
Historically GT has never overclocked ULV recipes, and a relatively recent change by Arch changed the math so now it does. Long story short just glossing through JEI there are quite a lot of recipes to change for the pack, so trying to get the recipes changed in base GTCE itself instead. 

Either way we agree it's pretty bad gameplay design to require exact voltage amps otherwise it would just defeat the purpose of cables, but there isn't a quick fix or this one unless it's in base GTCE.

**Comment by Turmfalke2** [comment]
There appears to be a fix in GTCE 1.7.1:

* Allow toggling overclocking via GUI button for electrical machines.
