### ISSUE TITLE
FTB Interactions 1.3.0 Dedicated Server crash on startup - Fluxnetworks load error.

### ISSUE THREAD

**Issue by BlubbPaule** [FTBTeam/FTB-Interactions#533]
## Modpack Version: 
1.3.0

## Bug Report:
Server Crash on Startup.

## Expected Behavior/Suggestions:
It should start..

## Is It Repeatable? Steps to Reproduce: 
For me yes, just starting the server.

## Link to Log or Crash File Paste**: 
https://pastebin.com/c3uzpX83

## Mod/s Affected: 
fluxnetworks           

"Exception in server tick loop"

"net.minecraftforge.fml.common.LoaderException: fluxnetworks Failed load class: sonar.flux.FluxNetworks     "

**Comment by Vyraal1** [comment]
Honestly not too sure what might be the cause here - could try updating to latest Java but that's a longshot. Did you make sure all the mods were in the folder/installed correctly? If so, going to forward this to the mod dev.

**Comment by Gunner76th** [comment]
Line 225 of the crash report identifies that   fluxnetworks-1.12.2-3.0.19-21.jar  is the mod causing the crash during mod construction and loading. Additionally line 68 identifies the cause as a Class not found exception for the class sonar.flux.FluxNetworks, which itself appears to be caused by the issue identified in line 77 which is an Array out of bounds exception error. It is possible that during the download process of the pack, a couple of bits/bytes of data got messed up and corrupted the data file resulting in the aforementioned errors. 

I would suggest deleting the mod file fluxnetworks-1.12.2-3.0.19-21.jar  from the mods folder, and then redownload that mod only directly from the mod's curse/twitch page, making sure you download the correct version. Here is a link for FluxNetworks https://minecraft.curseforge.com/projects/flux-networks/files/2645165

You might also want to try replacing the Sonar Core with a fresh download. Its link is here: https://minecraft.curseforge.com/projects/sonar-core/files/2645156

While most likely unrelated, but should be done for security and bug fix reasons, your Java version is out of date. You are on update 151, however current release is version 211. A java update is recommended.

**Comment by BlubbPaule** [comment]
Gunner76th was right. I redownloaded, reinstalled and reuploaded the server onto my server rig and now it works just fine. Something went wrnog the first time.

Thats some detailed stuff you wrote there, i'm impressed. Thanks and best regards <3
