### ISSUE TITLE
On upgrade, user is given questionless prompt.

### ISSUE THREAD

**Issue by Torrenal** [FTBTeam/FTB-Interactions#537]
## Modpack Version: 
1.3.0

## Bug Report:
When upgrading the modpack (from 1.2.1 to 1.3.0), and loading my old save, I'm given a prompt...
"Forge Mod Loader detected missing registry entries.
If you continue the missing entries will get removed.
A world backup will be automaticall created in your saves directory.
Missing items blah blah blah

[Yes]   [No]"

So evidently I'm expected to select Yes or No.  But no question was asked.
Is it "Continue loading anyway?"  or "Cancel loading this save?" or even "Delete all saves and start over?"   

## Expected Behavior/Suggestions:
When the user is presented with a Yes/No prompt of any type, it should be paired with an explicit question.

## Is It Repeatable? Steps to Reproduce: 
![questionless prompt](https://user-images.githubusercontent.com/23144113/57007019-afcf8e80-6ba2-11e9-9949-2a12466bdd79.png)
Load a 1.2.1 or older save into 1.3.0

## Link to Log or Crash File Paste**: 
N/A
## Mod/s Affected: 
Forge Mod Loader

## Known Fix: 
N/A

**Comment by Gunner76th** [comment]
Have you tried repeating this error with the GUI size changed to large/auto/normal? It may be an issue in that the text isnt being displayed due to the GUI size. That setting is found in the Video section of the settings menu.

**Comment by Vyraal1** [comment]
What Gunner said, the Yes or No is just a reference if you want to continue loading the world or not. This is the standard forge prompt for whenever it realizes that the registries have been altered due to a removal of a block. For servers, they will get a prompt on their console to type in `/fml confirm'. 

Regardless I still think this is a non-issue, we still have dev-worlds where we test for possible corruption, for the most part you can assume that any releases should still have continuity for all world saves.
