### ISSUE TITLE
give fako credit for the chicken textures

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#55]
Submitter: `Vyraal1#0001`
Body: `OwO issue "give fako credit for the chicken textures"`
Attachments:

**Comment by Saereth** [comment]
What did you have in mind for this @Vyraal1, I definitely want to honor/credit the people that provided time and assets to the pack like fako im just not sure the best way for us to present it.

**Comment by Vyraal1** [comment]
For DJJ I did quests for Euclydes/portals 
![image](https://user-images.githubusercontent.com/26587049/55170415-e2720b80-514c-11e9-99eb-9a6139cf3916.png) since its the most one-time visibility.

For Fako I wrote this 
![image](https://user-images.githubusercontent.com/26587049/55170651-4eed0a80-514d-11e9-98f2-472b3ebcfac3.png)

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55170890-bd31cd00-514d-11e9-8600-ecffc7c95888.png)

**Comment by Saereth** [comment]
peeerfect!
