### ISSUE TITLE
Early game (void world) feedback

### ISSUE THREAD

**Issue by twothe** [FTBTeam/FTB-Interactions#571]
I just finished progressing through the void world part (v. 1.4.2) and like to give some feedback:

Overall the experience was good. After some initial confusion with all the changes the pack made, I was able to understand most of the concepts thanks to the great questlines. I found some aspects a bit tedious though and would love to see some support on the early game to make it more enjoyable (see below). Other than that I had a blast, and I am looking forward to Overworld progression.

- I wish I knew beforehand that dirt is actually the best building material: it is cheap, it doesn't burn, and it doesn't allow Endermites to hide and kill me. Maybe there should be a hint for that.

- The Overworld portal description scared me as I thought a horde of mobs would invade as soon as I open it or they are waiting on the other side. But actually nothing happened aside from a lone Zombie. 

- That constant breaking of tools is very annoying. While flint tools are easy to produce (as soon as you have some EC) constantly having to run back and make some after what feels like every second tree cut down is a pain. I would like to see some low-tier Tinker's tools here, those would take out some of the annoyance. 

- Constantly having to maintain trees is a bit annoying once you progressed a bit. You get automation for the Kiln, the Water Powered Saw, and even the drying racks, but yet you still have to punch those trees. I'd suggest to add Bonsai Trees mod and allow crafting of the hopper version about mid-way through the void world. 

- Keeping nutrition up is super annoying. Even though I have plenty of food I don't really feel like browsing through thousands of cooking recipes. You might want to consider allowing the kitchen multiblock early game to ease the crafting of those.

- The spawning of mobs via infinity dust sounded like something I should do, but aside from some ender pearls I didn't really feel like it was worth doing it. Maybe change the wording on that questline to note that those items are required much later.

- The hunger drain when hitting wood with the axe for bark is insane and also completely pointless. I never felt like there is any reason to do that, as all you get are torches. Since mobs cannot spawn in the void world anyways, I don't really see the reason why torches are gated like this. I feel that the hunger drain is just out of place, having to hit logs with the axe is annoying enough to make torches scarce.

**Comment by Karthas077** [comment]
1. Dunno what to say here. I've never used infinity dust to spawn monsters so I never ran into that problem.
2. You must have gotten fairly lucky with where your portal spawned then. Mine dropped me in the middle of a chasm where mobs spawned even during the day. Barely managed to wall off a section before dying to the three skeletons that rushed me.
3. There is an early game tinkers hatchet. takes six gravel (turned into two flint) and two cobblestone (turned into stone rods) and can be crafted in the 2x2 inventory... There's even a quest that requires you make those, and they can be repaired (instead of re-crafted) as soon as you go to the overworld and get a single bucket of mana.
4. I haven't the faintest idea what you need that much wood for.
5. Kitchen multiblock is available pretty early, and you can search JEI for tooltips to find out what foods satisfy which nutrients. It's fairly easy to maintain pretty decent values by pumping Protein/Grain/Vegetable to 100 first, and then drinking fruit juice and milk which can be consumed even while saturated.
6. You should be able to look at the other quests and your personal goals and tell whether or not you need to grind mobs.
7. As far as I can tell it's intended to discourage you from processing wood manually and switch over to using either the manual saw or the water powered saw as early as possible. The bark is more of a consolation than anything and should really not be farmed. Using candles until you find a Menril tree and then switching to Menril Torches is by far the easier route.

**Comment by Vyraal1** [comment]
Hi thanks for the feedback, I'm going to go through each off the bullet points and try to explain 

1) We want to give players the bare necessities and give them credit that they can figure out solutions to the problems presented. If they can't figure out dirt is a good building materials, that's really on them, not on us (no offense).

2) That's the nature of RNG, better to set expectations rather than come back to angry complaints they get got cheap shotted.

3) You actually do have low tier tinkers tools such as the (we renamed it to Rudimentary). Either way, that's the part of the early progression, it may not feel worthwhile gameplay and in fact I agree with you that is one of the less enjoyale parts of the pack, but unfortunately that's the nature of the progression, and buffing things early on defeat's the purpose of it.

4) GT Axe has a timber functionality, and similar to before the concept of hopping bonsais really goes against the ideal of the pack. It's about mod interactions to make an automated tree farm, not a one fit all solution. Not to mention it encourages gameplay we don't want, such as mass spamming of hopping bonsai trees rather than a more established tree farm. Going to have to say hard no to hopping bonsais, it would also be a nightmare to balance.

5) Kitchen multiblock can only help so much since it relies on 3x3 crafting recipes, which we have altered for key recipes like dough (which needs basin) or bread (which needs furnace). Managing the information overload is part of the pack and the organization, short of a cheatsheet/guide (which really just goes against our policy of having players figure stuff out themselves). We won't stop people from creating guides or sharing tips socially, but we really don't see an advantage to always telling the player the best routes.

6) Could look into it, but the questbook isn't the end all, be all. In fact the questbook straight up just gets worse imo as the player really needs to stand on their own two legs using their mod knowledge and JEI. After a certain point it's only there to tell players what might be unintuitive, isn't common mod knowledge, or custom changes to the pack. We prefer to let players know when the soonest they can craft or do something. Either way if we move it later, there is a high chance someone else would say "I wish I knew about this sooner! Why don't you move it up?". So from my perspective it's an unwinnable battle.

7) Its to incentivize getting to automation and wood powered saw as soon as possible. Even if the quests were there, I really believe players would just ignore using Artisan Worktables, or water powered saw if it was just easy to do it manually. The fast drain rate is there to communicate that you need to set up infrastructure, and short term solutions never go anywhere.

**Comment by twothe** [comment]
1. Well I figured it out after I died a few times. ;) 
The issue is that I am an experienced Minecraft player, so I planned carefully and managed to come up with a solution to the Endermites while only dying 5 times in the process. Less experienced players might at this point have to restart the pack as having an Endermite at your spawn point means you die moments after respawning without any chance to even find them. So the problem essentially boils down to Endermites I guess.

2. Well that scares me again considering that I am about to explore the Overworld. :D Maybe I just got lucky with my spawn-point. But I secured it just in case... *paranoid look*

3. The questbook also suggest to throw the tinker's axes away if they break, which made me replace them with the GT axes asap. Maybe I am just too spoiled by all the infini-tools from other packs.

4. Well then there is also Progressive Automation: it handles the tree-cutting, requires setup & maintenance, it interacts with other mods as it actually uses the tool provided, it is easy to balance from a mod-creator perspective and would solve the issue of tediousness. 

6. I agree that the questbook shouldn't take you by the hand through the whole mod, but it is more or less a requirement for the first steps until the player gets some grasp of how things work. The problem is the combination of extremely challenging mobs (at that point of progress) vs the result. If the book suggests it as a possibility people will think that they need that stuff soon for another quest, but I am pretty sure Ender IO is not on the list of things I will encounter anytime soon. ;) So I built that mob farm, died several times, almost had to restart, all for nothing. That feels a little discouraging, which is bad so early into the pack.

7. Well you can automate the Water Powered Saw the moment you have it with hoppers and water. I would never want to do anything manually if I don't have to, so the very last thing I would do would be to use the axe to cut wood. The big problem I see here is that at the point you do it you have no food supply, so using the axe a few times too often will essentially break the game. Now if there was a reason to gate whatever you get out of that I could agree with it, but then there is nothing gated here. Torches are irrelevant for that stage, and if people really want to cut wood in a very tedious way, well.. if it entertains them then why not?

**Comment by krakel** [comment]
@Karthas077 If you want to have Grains of Infinity you can it get only from these Endermites. :)
