### ISSUE TITLE
Inconsistent clay to brick recipe

### ISSUE THREAD

**Issue by Doppelganker** [FTBTeam/FTB-Interactions#58]
## Modpack Version: 
1.00

## Bug Report:
You are able to smelt clay directly to brick in kiln, but you need to convert them to unfired clay bricks for smelting in furnaces.

## Expected Behavior/Suggestions:
With likely intended removal of Brick wooden form, there should be clay to bricks in furnace.

## Is It Repeatable? Steps to Reproduce: 
yes. Check brick recipes.

## Mod/s Affected: 
Vanilla, GT + shadow's addon

**Comment by Saereth** [comment]
this is actually not a bug, you need to automate the unfired bricks in order to use the much faster direct smelt recipe, otherwise the kiln clay recipe is for early game when you cant access a gt saw yet to make the mold but obviously takes far longer to cook in a kiln then a high speed furnace later.
