### ISSUE TITLE
Industrial Foregoing Pumps dupe liquids

### ISSUE THREAD

**Issue by tfs12** [FTBTeam/FTB-Interactions#627]
## Modpack Version: 
1.6.0

## Bug Report:
Industrial Foregoing Pumps extract full buckets from flowing liquids, replacing them with cobble.
This means you can put a bucket 1-2 blocks above the collection area, let it spread out and fall, and have a fairly quick nearly infinite liquid generator for very little cost.

## Expected Behavior/Suggestions:
The pump doesn't pick up flowing blocks.

## Is It Repeatable? Steps to Reproduce: 

1.  Place an industrial foregoing pump above an air block.
2. Place a range addon in(e.g. a range addon +5), add power.
3. Place a liquid 1-2 blocks above, on a small platform that lets it spread out.
4. Let the liquid fall a long way(all the way to the bottom in the void world); the pump will follow the liquid down to choose blocks to turn to cobble.
5.  Place a single bucket of the liquid directly under the pump; this will set the liquid filter, and the pump will begin producing 1 bucket every 33 ticks. This must be done last; otherwise the pump will cobblify this 1 source block and stop. It's possible the pump may randomly choose this block to turn to cobble and thus stop the pumping action, but this didn't happen in ten minutes of watching it. It did create lots of cobble down near the void where it was taking the liquid from.

This is the setup I used(the sandstone block is where I would put the liquid):

![2019-05-17_15 20 53](https://user-images.githubusercontent.com/50752144/57951237-7c397780-78b7-11e9-8765-c73cb1b9e035.png)

This is what it looks like near the void after about 10-15 minutes:
![2019-05-17_15 25 41](https://user-images.githubusercontent.com/50752144/57951447-14376100-78b8-11e9-87db-540f0948f56e.png)

That's basically a cube of cobble, and constantly spreading out diesel. I think it will eventually start hitting flow length limits and every possible location for liquid will get turned to cobble, but that will take a while.  At this point I have 700 buckets and if it does hit that limit, I suspect it will be in the 10s of thousands of buckets.

It trivializes powergen and give you a nearly infinite supply of anything that can be transformed to liquid form, for a small amount of power and an lv-tier machine.

## Mod/s Affected: 
Industrial Foregoing

## Known Fix: 
Don't use it.

**Comment by Vyraal1** [comment]
We picked this pump because it had the appropriate range and tps performance to pump out oil geysers compared to others we've tested and enabled. Forwarded it to Buuz, hopefully he can get a fix for it.

**Comment by Xela10001** [comment]
![image](https://user-images.githubusercontent.com/47480171/58382695-5736ba00-7fc5-11e9-972c-ac6ee7614b48.png)
 
Here is an improved setup, i noticed this bug when the pump didnt cobble source blocks when i used it to extract mana from mana pools.
As long as the cobble block below the pump is destroyed before the next "work", it will keep pumping. If not, the pump will stop and it has to be replaced for the bug to continue.
Knowing this, this is a block breaker on redstone signal only going through the cobble block and activating it, with the watch of flowing time making the setup faster (Can't add more than 1 or the setup bugs).
That is a single oil source block and here is the result
![image](https://user-images.githubusercontent.com/47480171/58382727-a67cea80-7fc5-11e9-8786-826c1e6557f5.png)

BTW, when trying to make this setup before, i placed a piece of redstone on the ground and my game insta crashed, and everytime i tried to log into that world my game crashed. [heres the crash report.](https://pastebin.com/SAhJbZU9)

Im writing this in hopes it gets fixed, good luck fixing it because i really dont want to use gregtech pumps for oil geisers
