### ISSUE TITLE
Tinkers.zs Script Update 

### ISSUE THREAD

**Issue by bookerthegeek** [FTBTeam/FTB-Interactions#628]
## Heyo 
If you take lines `#525` & `#526` in the Tinkers.zs file which is currently;
```
recipes.remove(<tconstruct:smeltery_controller>);
<tconstruct:smeltery_controller>.addTooltip(format.darkRed("Disabled, this is still left in JEI because hiding it also removes the Smelting tab that the Porcelain Melter inherits."));
```
and replace them with the following;
```
mods.jei.JEI.removeAndHide(<tconstruct:smeltery_controller>);
mods.jei.JEI.hideCategory("tconstruct.alloy");
```
Then it will remove the smeltery controller and the alloy section for it in JEI while leaving the Smelting tab that the Porcelain Melter uses.

**Comment by Vyraal1** [comment]
We left it that way because one of the most common questions we kept getting was "Is the smeltery disabled?" even though it was hidden from JEI. So we reverted from the removeAndHide.

Also last time we tried, removeAndHiding the the smeltery also removes the recipes that the porcelain melter inherits (Melters own JEI integration is lackluster, it can smelt a lot of the custom GTCE add ores, but it doesnt display that). Unless this behavior changed, I think we still have to leave it this way.
