### ISSUE TITLE
Inconsistent item drops for dense ores

### ISSUE THREAD

**Issue by Matt8898** [FTBTeam/FTB-Interactions#634]
## Modpack Version: 
1.6.0-1.12.2
## Bug Report:
Breaking a block of dense ore(tested with iron and gold) with any form of automatic block breaking results in 64 of the dense ore being dropped, after some time it stops dropping altogether, even from a normal pickaxe.
## Expected Behavior/Suggestions:
It should drop one ore.
## Is It Repeatable? Steps to Reproduce:
Drops 64:
https://streamable.com/12ghm1
Drops 0:
https://streamable.com/fgt27
Restarting the server fixed the drop issue for a while
## Mod/s Affected: 
Any mods that adds an automatic block breaker can do the 64x drop

Update: 
Drop multiplication seems to happen when the block is harvested by an automatic miner except for the block breaker from random things, the behaviour seems fairly inconsistent, it can either not drop any item or the drop amount has 2^n growth where n is the amount of times the block was broken by an automatic miner, this goes up to dropping 64 of the block.

**Comment by Vyraal1** [comment]
Damn it, this strikes again. 

https://github.com/The-Acronym-Coders/ContentTweaker/issues/147
https://github.com/Vyraal1/FTB-Interactions/issues/55
https://github.com/Vyraal1/FTB-Interactions/issues/28

Tbh we're not sure what is causing this, even the dev himself is unsure of it. I'll bring it up again since it has been a couple months that have passed since then. I haven't had time to recreate this with a minimal modlist yet, but I want to try.

**Comment by Matt8898** [comment]
Where can I find the scripts for the dense ores, I want to do some testing.

**Comment by Matt8898** [comment]
I've managed to replicate this glitch using just B.A.S.E, contentweaker, crafttweaker and extra utilities 2.

This is the code for the item:
https://hastebin.com/axazetetef.cs

**Comment by Matt8898** [comment]
I've compiled the latest dev version of BASE and the bug was fixed.

**Comment by Saereth** [comment]
updated base in the latest version, should hopefully be the end of this
