### ISSUE TITLE
Unbreakable creative mill

### ISSUE THREAD

**Issue by popcornCZ** [FTBTeam/FTB-Interactions#636]
## Modpack Version: 
1.5.0

## Bug Report:
The Creative Mill from ExtraUtils2 is unbreakable. And its source of GP. 

## Mod/s Affected: 
Extra Utilities 2 

## Known Fix: 
Set to true this in extrautils2.cfg : 
"creative blocks: breakable" {
    # Allow Non-Creative players to break/harvest creative blocks. [default: false]
    B:gameplay=false 
}

and also this: 
"creative blocks: configurable" {
    # Allow Non-Creative players to configure creative blocks. [default: false]
    B:gameplay=false
}

**Comment by Vyraal1** [comment]
What purpose does that latter config change serve? Does the creative mill have additional config options ingame? If it's for other blocks, there shouldn't be any other creative blocks in XU2 available.

**Comment by Saereth** [comment]
the second one would allow things like the creative drum to have its fluid type set, this should remain off imo as it has potential admin uses and allowing players to change them invalidates those admin uses. They are also otherwise unobtainable except for the mill which has no configuration options. The first config did need to be changed tho.
