### ISSUE TITLE
License of GTCE was deleted

### ISSUE THREAD

**Issue by krakel** [FTBTeam/FTB-Interactions#637]
the license of GTCE was deleted some hours ago, now we are no longer allowed to use this
https://github.com/GregTechCE/GregTech/commit/7472ef2847561c21c9c9fbef3760c30cb3a1928a

**Comment by thePalindrome** [comment]
Firstly, we pulled GTCE from a time when it was still covered under GPL-3

Secondly, the code is *still* under GPL-3, since there are 48 other contributors, and I'm not seeing a concensus between all of them to remove the license

Thirdly, GTCE is on curseforge, which has, as part of its TOS that the mod is available (because that's kindof how curseforge works, you put mods up so people can download it)

All in all, we're fine, Arch is just doing some cleaning/moving on the repo itself.

**Comment by Saereth** [comment]
@krakel thats now how licenses work, we're fine and will continue to be fine despite what arch does
