### ISSUE TITLE
Follow up: Moon has wrong biomeIDs, also has no moon's ores and moon dirts #695

### ISSUE THREAD

**Issue by bigfootbrz** [FTBTeam/FTB-Interactions#710]
I also have this exact issue. The planetDefs.xml file under the world gets replaced.

`[23:18:25] [Server thread/INFO] [advancedrocketry]: Checking for config at C:\Games\FTB Server.Interactions\.\world\advRocketry\planetDefs.xml`
`[23:18:25] [Server thread/INFO] [advancedrocketry]: Advanced Planet Config file Found!  Loading from file.`
`[23:18:25] [Server thread/WARN] [advancedrocketry]:  81 is not a valid biome id or name`
`[23:18:25] [Server thread/WARN] [advancedrocketry]: Invalid sky color specified`
`[23:18:25] [Server thread/WARN] [advancedrocketry]: Invalid sky color specified`
`[23:18:25] [Server thread/WARN] [advancedrocketry]:  0 is not a valid biome id or name`

_Originally posted by @bigfootbrz in https://github.com/FTBTeam/FTB-Interactions/issues/695#issuecomment-503755557_

**Comment by bigfootbrz** [comment]
There's two problems:
1) The biomeId is invalid because the extra space after the comma in `biomeIds` field
2) The biomeIds are shifted up by 2 according to level.dat

![level_dat](https://user-images.githubusercontent.com/2620240/59805205-e8612e00-92f0-11e9-9eeb-3f65bf90260d.png)



Simple fix for 1.7.0 is this:

`--- planetDefs.xml	2019-06-19 23:13:55.344391200 +0200
+++ planetDefs.xml	2019-06-20 00:13:46.443790400 +0200
@@ -23 +23 @@
-				 <biomeIds>72, 81</biomeIds>
+				 <biomeIds>74,83</biomeIds>
@@ -51 +51 @@
-			<biomeIds>73,80,0</biomeIds>
+			<biomeIds>75,82,0</biomeIds>
@@ -67 +67 @@
-			<biomeIds>74,77, 0</biomeIds>
+			<biomeIds>76,79,0</biomeIds>
`

**Comment by Exxion** [comment]
A fix for this would be very nice, since no moon turf means no tungsten.

**Comment by narwhalfire** [comment]
This can also be fixed by just using the registry name of the biome. Such a fix is the purpose of registry names, so that updates resulting in rearranged numerical ids aren't an issue. This wouldn't fix the issue of the spaces however, since that seems to be a problem of parsing the config. But, it doesn't matter if you don't put in spaces (aside from those that exist in advanced rocketry's registry names).

**Comment by Saereth** [comment]
maybe that's changed which would be great, last time I tried using registry names it didnt recognize them at all, had to  use the ids. I'll give it a try later. For now I removed the spacing anyway

**Comment by narwhalfire** [comment]
It may be the case that advanced rocketry only supported numerical ids in the config previously, but that would surprise me. I find it more likely that its config reader was unable to accurately parse the config due to the config not being formatted perfectly (which wouldn't surprise me seeing has how it doesn't handle extra white space very well). 

Forge's 1.12 registry system enforces lower case registry names, and will lower case the strings you give it. So even if you register like so [BiomeGenAlienForest.java#L22](https://github.com/zmaster587/AdvancedRocketry/blob/555b8cb131a69a46f609a46364c77bdc9a8aa932/src/main/java/zmaster587/advancedRocketry/world/biome/BiomeGenAlienForest.java#L22), the registry name would be `advancedrocketry:alien forest`. The [standard for RLs is snake case](https://mcforge.readthedocs.io/en/latest/concepts/resources/), which Forge says it enforces, but I guess here the space gets by (probably because it's just a biome). But that space actually needs to be in the name in the config. 

 This properly generates the planets with what I believe to be the intended biomes. https://pastebin.com/vY2Q53xW

**Comment by Saereth** [comment]
great work getting that working/formatted properly, will include in the next update with credit to you for it, thanks!

**Comment by narwhalfire** [comment]
You should credit @bigfootbrz as I just applied their fixes to the config. The xml I shared is just generated by advanced rocketry from that config.
