### ISSUE TITLE
Sky cauldrons do not work (for a different reason this time)

### ISSUE THREAD

**Issue by Buggy123** [FTBTeam/FTB-Interactions#734]
## Bug Report:
Sky Cauldrons will never craft anything. After the last fix to their config, their recipes load, but the time is not configured correctly:
![image](https://user-images.githubusercontent.com/16315400/60372409-88424a00-99ca-11e9-95db-e3d9f5eecdbf.png)

As a result, the sky cauldron controller will never craft anything, and it will always state "now is not the time for that":
![image](https://user-images.githubusercontent.com/16315400/60372522-d5beb700-99ca-11e9-85de-7b029ee761ca.png)
regardless of the time of day.

## Mod/s Affected: 
Modular Machinery, Modular Diversity

**Comment by Xela10001** [comment]
Can confirm

**Comment by Exxion** [comment]
The fact that it never works is caused by the recipe config files not defining the `modulo` value in the `daylight` requirement. It should be 24000.
However, it would desync from the actual time of day in certain circumstances if only that were changed, so `local` should also be set to `true` in the daylight requirements.
This is what the tooltip looks like if you make those changes:
![image](https://user-images.githubusercontent.com/9827785/61189519-7adcbf00-a65c-11e9-81b3-407fb00b6b1d.png)

Specifically, the changes required are to turn this block:
```
"type": "daylight",
"io-type": "input",
"start": 12000,
"stop": 0
```
into this:
```
"type": "daylight",
"io-type": "input",
"start": 12000,
"stop": 0,
"modulo": 24000,
"local": true
```
in each recipe.

**Comment by rptbuddy** [comment]
Exxion's fix did not help me with actually crafting the item, the tooltip did change however.

**Comment by Exxion** [comment]
Really? That's odd. I'll look into it more later

**Comment by rptbuddy** [comment]
I was on a server, however I changed both the server and my local configs when trying.  I removed the time requirement block and was able to craft it.  Personally don't think the time period should be required since the multiblock does require a celestial collector crystal to begin with but watevs.  If you think of something for me to try though I'll give it a shot.

**Comment by Exxion** [comment]
The changes I said above are definitely necessary to fix this, but apparently not sufficient. In fact it doesn't appear that *any* changes to the config make it work, other than completely removing the daylight requirement. This is probably a bug with Modular Diversity. My only suggestion there is to try updating it, since there have been some bugs related to the daylight component fixed since the version currently in the pack.

**Comment by dcirusc36** [comment]
to anyone wanting an actual working fix to this problem remove the following
"type": "daylight",
"io-type": "input",
"start": 12000,
"stop": 0
at the top 4th row in your editor make sure you have "recipeTime": 1200, this fix just removes the daylight requirement which in my mind is pointless because of the celestial collector crystal.
