### ISSUE TITLE
Suggestion: Thorium in reactors

### ISSUE THREAD

**Issue by Sirbab** [FTBTeam/FTB-Interactions#780]
## Modpack Version: 
1.91

## Bug Report:
No reactor based use for Thorium

## Expected Behavior/Suggestions:
Given there is a nuclear reactor of sorts, it stands to reason one should be able to utilize other radioactive chemicals like thorium, which in real life is a very viable nuclear breeder option.  

## Is It Repeatable? Steps to Reproduce: 
![image](https://user-images.githubusercontent.com/1490991/62522933-b9e7d580-b800-11e9-8ef1-426e2c7a8575.png)
(Only recipe for the reactor is with uranium, not a bug per se.)

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Gregtech/Modular Machinery

## Known Fix: 
If there is no plan to add a fully fleshed out reactor mod like reactorcraft or a stripped down version of IC2, then the photonuclear fission reactor should be able to use sort variant of thorium or thorium fluoride to produce steam.  It's frankly jarring to have a modpack of this technical depth without the ability to use multiple fissile materials.

**Comment by Saereth** [comment]
It boils down to game stating, thorium is available easier than uranium, so we could add thorium but it'd have to be less power than uranium, So this becomes a design issue since you can convert thorium to uranium with magic in this pack already, what's the relationship between converting the thorium to uranium first before using it or using thorium directly, we can quantify that in terms of eu for producing mana to some degree, but there are also infrastructure concerns and the like. Ultimately the thorium would end up just being a worse version of uranium that took less processing.   

I'm open to ideas but just directly using thorium as reduced rates compared to Uranium doesnt seem that interesting
