### ISSUE TITLE
Cyclic Empty Heart Container does not appear to have "cure"

### ISSUE THREAD

**Issue by silvanasmax** [FTBTeam/FTB-Interactions#802]
The Empty Heart Container item from Cyclic mod removed 2 hearts permenantly from my character.  A related find online seems to verify this: Jul 29 - https://github.com/NillerMedDild/Enigmatica2/issues/535

It seems any "cure" for this is missing in Interactions as well.  Given Cyclic's horribly lax documentation (online and in-game), it is impossible to determine what the fix could be.  This is a useless item to make, given what it does currently.

## Modpack Version: 
1.9.1 (public server)

## Bug Report:
Item removes 2 health permenantly, with no way to reverse effect.

## Expected Behavior/Suggestions:
Expected Behaviour: There should be a way to reverse the effect, or simply not have the effect in the pack.

Suggestion: Either remove Empty Heart Container, ensure a "cure" process or item is included, and/or provide documentation as to why this even exists.

## Is It Repeatable? Steps to Reproduce: 
Eat the Empty Heart Container.
Weap.

## Link to Log or Crash File Paste**: 
No log file or crash file generated.

## Mod/s Affected: 
Cyclic

## Known Fix: 
None

**Comment by Yakameen** [comment]
This bug is fixed in the version of Cyclic currently in the modpack, and I can confirm it now only removes one heart per container.

Adding the Heart Container back, but limiting to 10 hearts max seems like the way to prevent someone from permanently removing hearts without getting rid of the Empty Heart container from the pack. By limiting to, 10 someone can regain removed hearts, but not increase their total heart count before Baubley Heart Canisters.

**Comment by Saereth** [comment]
this is fixed in the new update with the cyclic update
