### ISSUE TITLE
Crying Obsidian doesnt set spawn when placed in overworld

### ISSUE THREAD

**Issue by Vend3tta** [FTBTeam/FTB-Interactions#81]
## Modpack Version: 

1.0.0
## Bug Report:

Used Crying obsidian to set spawn in the overworld, still respawn in the skyblock area
## Expected Behavior/Suggestions:

Spawn gets set in the overworld
## Is It Repeatable? Steps to Reproduce: 

1.Right click to set spawn crying obsidian. 
2.Get notification coords have been set as spawn point(done in the overworld)
3.Die
4. Respawn in Skyblock

**Comment by Saereth** [comment]
yeah void island control forces people to spawn in the void dimension so it only sets your spawnpoint there, not sure how we're gonna fix that yet

**Comment by Vyraal1** [comment]
Actually I think I found a fix for this, had a legacy script in the JED dimensions.json, but here's the situations:

1) Dies in Dim 0, Crying Obsidian in Dim 0: Spawns in Dim 0
2) Dies in Dim 0, Crying Obsidian in Dim 100: Spawns in Dim 0 (unlikely due to how safe Dim 0 is)
3) Dies in Dim 100, Crying Obsidian in Dim 100: Spawns in Dim 100
4) Dies in Dim -1, Crying Obsidian in Dim 100: Spawns in Dim 100
etc.
