### ISSUE TITLE
No way to add tank to non advanced rocketry chestplates

### ISSUE THREAD

**Issue by beastly123** [FTBTeam/FTB-Interactions#834]
## Modpack Version: 
1.9.1

## "Issue" Report:
Basically, what the title says, in other packs, there is generally a recipe that adds an oxygen tank to chest plates from other mods, but interactions has no way. Adding airtight seal to a chest plate won't create any slots for oxygen tanks to be inserted into

## Expected Behavior/Suggestions:
Add a way to add tanks to non-spacesuit armor sets

**Comment by Saereth** [comment]
I misunderstood the original bug report, I thought you meant you couldnt charge armors that had airtight seal with oxygen, I've confirmed they can be charged so this is intentional behavior, you can add airtight seal and fill your chest with the limited tank it gets from the airtight seal by standing on a chargepad or if you want a longer excursion suit for long exploration trips you can use the AR armor and put the larger size tanks in it, it's a trade off. Better protection+shorter air supply or longer air supply+AR Space suit levels of protection
