### ISSUE TITLE
Will there be an update from 1.9.1?

### ISSUE THREAD

**Issue by Ludi87** [FTBTeam/FTB-Interactions#855]
## Modpack Version: 
1.9.1

Greetings,

With the FTB App now released, and packs updating again, I'm just wondering if there will be an update to FTB Interactions aswell.

-Ludi

**Comment by KAfable** [comment]
Hi Ludi, sorry to be bearer the bad news, but for right now there is no plans to update the pack as most of us moved on to other projects. I will never say never, but it's extremely unlikely (bigger chance of Interactions 2 happening, which is already slim, and far off away).

**Comment by Cata-bre** [comment]
KAfable,

On the Interactions channel on the FTB Discord I noticed that a few months ago Saereth mentioned he was working on an update for Interactions. Is this update still in the works or has he moved on as well? Thank you for at communicating about the current status of FTB:I instead of leaving everyone in the dark.

Catabre

**Comment by iComputerfreak** [comment]
Also there was this: https://github.com/FTBTeam/FTB-Interactions/issues/788#issuecomment-533543070.

**Comment by Saereth** [comment]
Yes there will be an update, to get involved make sure you're joined to the FTB discord on the #interactions channel
