### ISSUE TITLE
Can't automate butter or cheese

### ISSUE THREAD

**Issue by paulsd95** [FTBTeam/FTB-Interactions#875]
## Bug Report: Can't automate butter or cheese

Cheese and butter can only be made via the primal mixer, mixing milk on its own or with salt. Once you get farther along it would be nice if the mixer machine could mix up some butter or cheese so you can fully automate some food making too...

**Comment by Cata-bre** [comment]
In a similar vein, is it possible to produce/automate Rustic alcohol from a GregTech Brewer?

Rustic alcohol has quality ranging from 0.0 up to 1.0. Is it possible to add a recipe that requires you have to insert 1.0 quality alcohol in addition to a quantity of the pre-fermented liquid to get 1.0 quality alcohol out? Requiring 1.0 quality alcohol means that players would have to progress through the Rustic brewing process once for every alcohol they want to produce at 1.0 quality.

**Comment by Cata-bre** [comment]
Another suggestion: Add a way to produce the ground meat from Pam's Harvestcraft with a machine.

**Comment by Saereth** [comment]
No on the rustic brewing, they rely on extra nbt data in the fluid which gregtech does not work with.

The other suiggestions are doable

**Comment by Cata-bre** [comment]
Would it be possible to add fluid extractor recipes for the liquids made in the rustic mashing tub?

**Comment by Saereth** [comment]
depends, which liquids/items specifically, if they have nbt data on the fluid no, if its a standard forge fluid yeah

**Comment by Cata-bre** [comment]
Most of the items already produce the associated fluid if placed in the fluid extractor. The only two fluids you cannot get from the fluid extractor are apple juice and honey.

Here are a few ofthe existing recipes:

Ironberry -> 250mB Ironberry Juice
Wildberry -> 250mB Wildberry Juice
Pam's Grape Juice -> 250mB Grape Juice

To make Apple Juice and Honey consistent with both the crushing tub and the existing recipes, I propose the following additions:

Apple -> 250mB Apple Juice
Honeycomb (Rustic) -> 250mB GTCE Honey
Honey (Pam's) -> 250mB GTCE Honey
Honeycomb (Pam's)-> 250mB GTCE Honey

Was the Rustic "Olive Oiled" buff removed because it made attaining full saturation too easy in the early game?

**Comment by Saereth** [comment]
yeah I can add those, and it was moved for both the saturation but also because there were a lot of complaints about the added jei clutter and increased load time as it generated all the recipes for the amount of foods we have

**Comment by TomiBelan** [comment]
It's already possible to automate butter and cheese. No need to add a new recipe for them.

- Insert milk with a fluid conduit
- Stir it with a Mechanical User set to "activate block with item"
- For cheese, insert salt with an Item Conduit + Limited Item Filter, or with Super Factory Manager
- Collect output with some kind of item collector
