### ISSUE TITLE
Suggestion: Logistics pipes recipes

### ISSUE THREAD

**Issue by flyingperson23** [FTBTeam/FTB-Interactions#907]
Remove the program compiler system and give everything a recipe that can just be crafted without the annoying 1.12 mechanics

**Comment by Saereth** [comment]
eh maybe, will leave this open for some discussion

**Comment by MaxNeedsSnacks** [comment]
Absolutely seconding this, due to the way the Request Table currently works you have to manually put away all other Program Compilers (I made about a dozen in bulk already because I don't want to have to recompile them over and over again) as well before you can request the components for a different logistics pipe, **AND** it seems the Logistics Bridge Result Pipe recipe is set up incorrectly to be non-sensitive to the Programmer's NBT so you can't craft pipes with the same ingredients (for example crafting pipes) unless you use a table that can disambiguate recipes (like the Request Table, for which you would NEED the crafting pipe, which at that point, it becomes a chicken vs. egg problem).

My personal suggestion would be to move pipe creation to assemblers (as you already need LV tech for any sorts of modules anyways) and then disambiguate them using different programmed circuits, so for 2 Iron, 2 Redstone, 1 Basic Chip and 1 Logistics Pipe, Provider Pipes would be circuit 0, Request Pipes 1, Supplier Pipe 2, and so on. Pipes with unique recipes like the different Chassis pipes or the Remote Orderer wouldn't even need a circuit in their recipes, of course, so that'd just get rid of an unnecessary extra step

**Comment by FakeLook** [comment]
yes please, that would be awesome.

**Comment by Hjaldar** [comment]
In my opinion the current system is OK. I made a few early pipes manually and then moved to autocrafting with Logistics Crafting Tables and leaving the correct flashed programmer in the table, so one table and flashed programmer per pipe recipe. It took some thought to work out what autocrafting system would work best given the constraints of the LP mod. I would suggest that in this pack that if you are making pipes in the Request Table for long you are doing it wrong.

I would definitely recommend against moving to a system of needing an Assembler with different programmed circuits per pipe. as that would probably result in assemblers with no other use except making specific LP pipes.

**Comment by MaxNeedsSnacks** [comment]
> I would definitely recommend against moving to a system of needing an Assembler with different programmed circuits per pipe. as that would probably result in assemblers with no other use except making specific LP pipes.
Most assemblers with specific circuit combinations (especially 0, 1, and 2) will be needed for a couple of recipes later on anyways, so with the maximum overlap of pipes with the same recipe being only 3 or so anyways it shouldn't make much of a difference.

> I would suggest that in this pack that if you are making pipes in the Request Table for long you are doing it wrong.
Fair enough, however it is still very much a nuisance to achieve and still requires copious amounts of Logistics Programmers for pretty much a single purpose.

**Comment by Heldenkrieger01** [comment]
Is it possible to "unlock" all recipes once you compiled everything in the compiler? That would be a good option, so once you have everything, you can just use a programmer, no matter whats flashed.

**Comment by MaxNeedsSnacks** [comment]
> Is it possible to "unlock" all recipes once you compiled everything in the compiler? That would be a good option, so once you have everything, you can just use a programmer, no matter whats flashed.

You would still have to disambiguate recipes then, which is what the compiler was originally introduced for.

**Comment by dominic-jones** [comment]
I figured this was just mod behaviour, and Logistics Pipes solves its own problem. Like Hjaldar, I just made a wall of Logistics Crafting Tables and forgot about it. If you want to add Assembler recipes, maybe, but I wouldn't see myself migrating. Moving to an Assembler that takes time/power, even if I could squash the 20 blocks into a single Assembler / Crafting Manager setup, doesn't sound worth it. 

But similarly there's no harm in adding it except maintenance/bug testing, so.

**Comment by Heldenkrieger01** [comment]
Yeah after playing for a bit longer I also feel like **the current system is OK**. The compiler merely delays the autocrafting of all the different pipes a little, since it's a bit expensive to craft this many crafting tables and pipes and programmers. Also a solution with the assembler would be worse in my opinion. Plus it's not that bad, since you can chisel the modules and upgrades!

**Comment by Saereth** [comment]
ok well I made the fluid pipes cheaper to mass produce anyway, gonna leave the rest as is for now, seems fine overall
