### ISSUE TITLE
Mineralis Ritual ContentTweaker ores not craftable to their Gregtech counterparts

### ISSUE THREAD

**Issue by Hekera** [FTBTeam/FTB-Interactions#991]
## Modpack Version: 
2.0.2

## Bug Report:
In order to fix the Gregtech blocks from not appearing at all, the mineralis ritual now generates ContentTweaker ores that cannot be crafted into their Gregtech analogues. This means that if you have a ContentTweaker BlockItem, it cannot be used for any recipes (besides covers) and cannot be used to complete quests. It has to be placed down and broken again either manually, or using conventional automated means. 

## Expected Behavior/Suggestions:
The blocks should have some sort of cheap/easily automatable recipe to convert them, like a packager recipe or something. I would avoid using _only_ normal crafting recipes simply because the large variety of blocks means you need more than one crafter for all the recipes if you were to automate the setup. Alternatively, give them oredictionary names that match their intended block/ore, so that recipes pertaining to their Gregtech versions also apply to them.

**Comment by Kortako** [comment]
I'm not exactly sure how you are getting the ContentTweaker version of the block as a drop, since they are intended to drop the real block upon mining.  I've had an automated Mineralis setup for a long time now (since 1.9.1, I'm now on 2.0.3) which breaks the blocks using Long Range Breakers, and those never drop the CT version of the block.  For testing, I also tried mining it manually with both my regular AIOT and a Silk Touch enchanted Fluxbore, and neither dropped the CT block but instead dropped the intended GT ore.  How are you getting the CT block?

**Comment by Hekera** [comment]
I'm using advanced drawbridges. They're cheaper and easier to craft, in addition to not requiring RF to operate.
